services:
  code-server:
    build:
      context: ./Docker/vscode
      dockerfile: Dockerfile
    container_name: vscode_container_nosql_lab
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ./workspace:/home/coder/workspace
    environment:
      - DEFAULT_WORKSPACE=/home/coder/workspace

  cassandra:
    image: cassandra:4.1
    container_name: cassandra_nosql_lab
    ports:
      - "9042:9042" # CQL
      - "7000:7000" # internode communication
      - "7001:7001" # TLS internode
      - "7199:7199" # JMX
      - "9160:9160" # Thrift (opcjonalnie, historycznie)
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:

# Code based on https://github.com/kjedrzejewski/podyplomowe_genai_public
# Well done Krzysztof!
