services:
  code-server:
    build:
      context: ./Docker/vscode
      dockerfile: Dockerfile
    container_name: vscode_container_nosql_lab
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ./workspace:/home/coder/workspace
    environment:
      - DEFAULT_WORKSPACE=/home/coder/workspace

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_nosql_lab
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage # - ./workspace/vector/qdrant_data:/qdrant/storage

  postgres:
    image: ankane/pgvector
    container_name: pgvector_snoql_lab
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  qdrant_data:
  pgdata:

# Code based on https://github.com/kjedrzejewski/podyplomowe_genai_public
# Well done Krzysztof!
